### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by KaimingHe** [pfrendl/he_init_variance#1]
Hi there,

There are several issues in your code.

The major issue is about which axis you compute the stats:
https://github.com/pfrendl/he_init_variance/blob/8e356f605bba9af937a87ace37990a2c7b573a82/main.py#L94-L100

In your case, it is `dim=0`, which means along the batch size. But the stats should not be about a batch; instead, it should be about all the activations in the same sample, so it should be `dim=1`. This is the critical problem.

There are some other minor issues. They don't influence whether the signal is diminishing or not; but they may matter for whether you are doing a relevant comparison.

In your code, your revised ReLU as:
https://github.com/pfrendl/he_init_variance/blob/8e356f605bba9af937a87ace37990a2c7b573a82/main.py#L13-L16
then you compare "lecun_init/glorot_init + no activation" vs. "lecun_init/glorot_init + sqrt(2) * ReLU activation". This is not the point of the comparison. The comparison is to compare "lecun_init/glorot_init + ReLU activation" vs. "lecun_init/glorot_init + sqrt(2) * ReLU activation". And under your revision, this is the right simulation for the underlying comparison of "lecun_init/glorot_init + ReLU" vs. "he_init + ReLU". And this is the comparison between "vanishing vs. not vanishing".

Hope this helps.

**Comment by pfrendl** [comment]
Hi,

Reducing along dimension 0 is intentional. The issue with reducing along dimension 1 is that you can have mean=0 and variance=1 with no signal propagation.

To demonstrate this, I have updated my code to also produce the plots for dim=0 reduction, and though I realize this is unrealistic, I have increased the network depth to 1000 to make my point obvious.

Reducing along dimension 1 results in these statistics:

![plot_dim1_ReLU](https://user-images.githubusercontent.com/6968154/223565220-b6157ecc-b951-4337-86e0-f57ff06232a0.png)
![histogram_dim1_ReLU](https://user-images.githubusercontent.com/6968154/223565248-fa2c69c3-bd04-4853-b362-f3dd1ef341c3.png)

The variance does shift, but this is to be expected to some extent because of the randomness and network depth.

However, these are the featurewise statistics (reduced along dim=0):
![plot_dim0_ReLU](https://user-images.githubusercontent.com/6968154/223565393-0526e40c-f229-4d73-86e8-c064ef9665ca.png)
![histogram_dim0_ReLU](https://user-images.githubusercontent.com/6968154/223565427-cf45f356-fa87-490b-afe0-a79e1e7c8c8d.png)


As you can see, the features are almost constant: over half of them have a standard deviation below 0.04 over the input data, and virtually all of them have a std below 0.1. The reason why we get variance over the feature dimension is because the features have means that are high in absolute value. However, these values are almost completely independent of the input.

The point of the comparison I made against the LeCun init + no activation variant is to demonstrate that without the sqrt(2) * ReLU component, the input signal does not diminish, except for random fluctuations. These are the dim=0 plots for this case:

![plot_dim0_Identity](https://user-images.githubusercontent.com/6968154/223565559-26c0818f-62ad-40d9-bbec-e105045071a0.png)
![histogram_dim0_Identity](https://user-images.githubusercontent.com/6968154/223565581-6bee464b-e53a-4dfc-a34c-cd2268074cf8.png)

As you can see, there is a qualitative difference. The SELU activation for example also preserves featurewise variance:

![plot_dim0_SELU](https://user-images.githubusercontent.com/6968154/223565632-81b1513c-8c86-4df7-9954-5e0c92f4c199.png)

Variance along dim=1 doesn't imply signal propagation, and with sqrt(2) * ReLU, the signal diminishes significantly in these examples.

**Comment by pfrendl** [comment]
I pushed the code for these measurements.

**Comment by KaimingHe** [comment]
Your criticism is because you misunderstood our work. The stats in the paper are computed over channels (`dim=1` in your code, or more precisely, `dim=-1`). If you don't include `dim=1` into the stats computation, it is simply not what we are computing.

Using your code, computing `dim=1` with `sqrt(2) * x.relu()` (which you used to simulate "he_init + ReLU") has this following result (y-axis limits set to reduce misleading). It is not perfect (because the assumption of the derivation is not perfects), but this signal does not vanishing (compared with the next figure):
<img width="935" alt="Screenshot 2023-03-07 at 3 09 37 PM" src="https://user-images.githubusercontent.com/11435359/223574908-8bbe16e5-3ffd-44da-b9e2-7a5fd377b37d.png">

And computing `dim=1` with `sqrt(1) * x.relu()` (which is "glorot_init + ReLU") has this following result. And it vanishes very quickly. And this is the comparison we were talking about in the paper.
<img width="927" alt="Screenshot 2023-03-07 at 3 10 36 PM" src="https://user-images.githubusercontent.com/11435359/223575030-05330b63-380c-464c-8a07-5f25de9b11c5.png">

It is ok to include `dim=0`; but it is not correct to **only** compute `dim=0`. You should use `dim=[0, 1]`, otherwise it is just not we were deriving. To do so, your code should be revised like this:
<img width="535" alt="Screenshot 2023-03-07 at 3 17 07 PM" src="https://user-images.githubusercontent.com/11435359/223576358-b7a6fd7c-af4d-495c-ae81-0deb415a6d1e.png">


And this is the result of `dim=1` with `sqrt(2) * x.relu()`. Again, it is not perfect (and its concrete shape depends on the random seed), but it is not vanishing:
<img width="916" alt="Screenshot 2023-03-07 at 3 13 41 PM" src="https://user-images.githubusercontent.com/11435359/223575465-367fea31-7784-4eed-bb85-bc63e011e707.png">


And again, `dim=[0,1]` with `sqrt(1) * x.relu()` is vanishing:
<img width="929" alt="Screenshot 2023-03-07 at 3 12 43 PM" src="https://user-images.githubusercontent.com/11435359/223575300-7efd8930-a2b5-4feb-aecb-c8785ea5c544.png">

I hope this will convince you.

I am not going to delve deeper. But I hope the community won't be misled by your claim.

**Comment by pfrendl** [comment]
I am not arguing that you are computing statistics along dim=0 in the paper. I also don't argue that the proposed approach is better than LeCun init for ReLU networks. These are not my points.

I am arguing that having mean=0 and var=1 over dim=1 or dim=[0, 1] is not a sufficient condition for preserving the input signal over many layers, although the paper makes these statements:
Page 4:
![image](https://user-images.githubusercontent.com/6968154/223583168-e19b1045-8cb5-47f6-9cfc-6f97db2e8cec.png)
Page 5:
![image](https://user-images.githubusercontent.com/6968154/223583280-2bcd74bc-9b93-4cf9-953c-bfd8f54f4f48.png)

In the example setup in this repository, I show that layers constructed using the proposed method diminish the input signal, resulting in close to constant preactivations after many layers. This goes against the statement that
"the variance of the input signal can be roughly preserved from the first layer to the last".

Preserving the input signal is different from preserving the input variance across the feature dimension. Again, the approach works better for ReLU than the alternatives, but speaking of misleading, your paper makes misleading claims about preserving signal variance.

**Comment by KaimingHe** [comment]
It is a valid motivation of considering any other axis, including `dim=0` you considered. And all the normalization methods published later (BatchNorm, LayerNorm, InstanceNorm, GroupNorm) are related to this decision.

But the derivation of our work is based on another consideration (axes at least include `dim=-1`). I hope the readers will be aware of this context.
